def printlogo():
    print(" _ __ _ __ _ __ _ __ _ __ _ __ _ __")
    print("|                                  |")
    print("|  Whats in the News???            |")
    print("|                                  |")
    print("|      #####  ####  ####  #   #    |")
    print("|      #      #***  #***  #*#      |")
    print("|      #  ### #***  #***  #*#      |")
    print("|      #####  ####  ####  #   #    |")
    print("|                                  |")
    print("|                                  |")
    print("|__      __ _ __ _ __ _ __ _ __ _ _|")
    print("   \    /")
    print("    \  /")
    print("     \/")
